### ISSUE TITLE
Address field edit window is not persistent. It should be.

### ISSUE THREAD

**Issue by RickKukiela** [barrelstrength/craft-sprout-fields#100]
### The problem (description, use case, screenshots...)
Sort of a bug depending on how you look at it. When editing the address field if you accidentally click off the layer it closes it, and trashes anything you've entered in causing you to have to re-enter. 

### The solution (that feature you'd like to see)
You should only be able to close the editor by clicking the cancel button.

**Comment by BenParizek** [comment]
Thanks @RickKukiela 

I'll look into this after we get through the 3.4 updates.

**Comment by BenParizek** [comment]
This has been addressed in Sprout Fields v3.8.1
