### ISSUE TITLE
'cms_sproutfields_addresses_old' already exists

### ISSUE THREAD

**Issue by laurabennett** [barrelstrength/craft-sprout-fields#102]
### Description (screenshots, logs, ...)
Database Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cms_sproutfields_addresses_old' already exists
The SQL being executed was: RENAME TABLE cms_sproutfields_addresses TO cms_sproutfields_addresses_old

Migration: barrelstrength\sproutfields\migrations\m200102_000000_remove_address_field_content_column_sproutfields

### Steps to reproduce

I've probably gotten into a bad state by attempting multiple failed upgrades. Can I just manually delete the table?

### Additional info

- Craft version: 3.3.0.1
- PHP version: 7.0.33
- Database driver & version:  MySQL 5.5.5
- Plugins & versions: Sprout Fields | 3.4.4

**Comment by BenParizek** [comment]
@laurabennett Yes, that sounds like an upgrade failed. That `sproutfields_addresses_old ` database table is a temporary table we use during a migration.

In general, it can be deleted from the database without breaking anything however you will probably want to make sure that the address field is behaving as expected and the address data you have has migrated to the new table and is all there. The fact the migration failed could signal other issues at hand. In the case you see anything missing, you may need to revert to a pre-upgrade db and run the upgrade again after you've ironed out any issues.

Let me know if you run into any other anomalies.

**Comment by BenParizek** [comment]
I'm closing this out. Please re-open or reach out to sprout@barrelstrengthdesign.com if any issues persist.
