### ISSUE TITLE
Composer error when upgrading from 3.4.4 to 3.6.2

### ISSUE THREAD

**Issue by lesaff** [barrelstrength/craft-sprout-fields#104]
### Description (screenshots, logs, ...)

```
Performing update with Composer ... error: An error occurred

Output:

<warning>Package "craftcms/vue-asset" listed for update is not installed. Ignoring.</warning>
<warning>Package "danielstjules/stringy" listed for update is not installed. Ignoring.</warning>
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barrelstrength/sprout-fields 3.6.2 -> satisfiable by barrelstrength/sprout-fields[3.6.2].
    - barrelstrength/sprout-fields 3.6.2 requires barrelstrength/sprout-base-fields ^1.3.4 -> satisfiable by barrelstrength/sprout-base-fields[1.3.5, 1.3.4].
    - Can only install one of: barrelstrength/sprout-base-fields[1.2.3, 1.3.5].
    - Can only install one of: barrelstrength/sprout-base-fields[1.2.3, 1.3.4].
    - barrelstrength/sprout-forms 3.7.2 requires barrelstrength/sprout-base-fields ~1.2.3 -> satisfiable by barrelstrength/sprout-base-fields[1.2.3].
    - Installation request for barrelstrength/sprout-forms 3.7.2 -> satisfiable by barrelstrength/sprout-forms[3.7.2].

<warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
```

### Steps to reproduce

1. Run `./craft update all`

### Additional info

- Craft version: `3.3.17`
- PHP version: `7.3.16`
- Database driver & version:  MariaDB `10.4.11-MariaDB Homebrew`
- Plugins & versions:
```
    - craft 3.3.17 => 3.4.15
    - aws-s3 1.2.5 => 1.2.7
    - amazon-ses 1.2.1 => 1.3.0
    - bugsnag 2.0.5 => 2.0.6
    - ckeditor 1.0.0-beta.2 => 1.0.0-beta.3
    - code-mirror 1.0.1 => 1.0.2
    - cp-clearcache 1.0.5 => 1.0.6
    - feed-me 4.1.2 => 4.2.1.1
    - field-manager 2.1.1 => 2.1.2
    - image-resizer 2.0.6 => 2.0.7
    - minify 1.2.9 => 1.2.10
    - redactor-tweaks 2.0.2 => 2.0.3
    - seo 3.6.2 => 3.6.4
    - sprout-active 2.1.0 => 2.2.0
    - sprout-fields 3.4.4 => 3.6.2
    - sprout-forms 3.6.5 => 3.7.2
    - super-table 2.3.1 => 2.3.3
    - twigpack 1.1.12 => 1.2.0
```
_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@lesaff It looks like you are still using Craft 3.3 and that composer is unable to reconcile a plugin requirement that will require you to upgrade to Craft 3.4.

Sprout Forms `barrelstrength/sprout-forms:3.7.2` and `barrelstrength/sprout-fields:3.5.5` are the releases to install to stay compatible with Craft 3.3. 

I've haven't found the best place to note this yet but you can see a list of all our Craft 3.3 compatible versions here: https://craftcms.stackexchange.com/a/33805/115

Let me know if that helps get things resolved.

**Comment by lesaff** [comment]
@BenParizek, follow up update

I have managed to get my Craft to update all plugins/core (to 3.4.x) by doing the following:

- Disable `sprout-fields` from the CP
- Delete  `sprout-fields` from `vendor/barrelstrength` folder
- Delete `sprout-fields` from `composer.json`
- run `./craft update all`

Cheers,
Rudy
