### ISSUE TITLE
It seems you removed the Template field, was this intentional?

### ISSUE THREAD

**Issue by mrunkel** [barrelstrength/craft-sprout-fields#106]
### Description (screenshots, logs, ...)
Existing fields still work, but you can't add or edit them in the panel.

In the commit b293ad9616e2e02894e2817422a38c44224861df, you removed the Class Import for the Template field.  

### Steps to reproduce

1.   Try to use the Template field.
2.  or Try to edit a Entry that uses the Template field.

In the first case, it's nowhere to be found.
In the second case, "Address" is shown instead as the field type.

### Additional info

- Craft version: 3.4.16
- PHP version: 7.4.4
- Database driver & version:  MySQL 8.0.19
- Plugins & versions: SproutForms 3.9.0.1 and SproutFields (3.6.2)

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@mrunkel Template field is being registered again in v3.8.0.

It appears to have been accidentally removed when running some PhpStorm inspections so I'll review things more closely when taking those actions in the future.
