### ISSUE TITLE
Layout issue with sprout address field

### ISSUE THREAD

**Issue by vsteenhoudt** [barrelstrength/craft-sprout-fields#114]
### Description (screenshots, logs, ...)
The address field layout seems to be broken. Looks like it is only recently introduced. Can't really say when it broke.
![image](https://user-images.githubusercontent.com/8911752/94279152-02ee7200-ff4c-11ea-9ba6-c1a7ab7b2988.png)

### Additional info

- Craft version: 3.5.11.1
- PHP version: 7.2.15
- Database driver & version:  MySQL 5.7.26
- Plugins & versions: 

Asset Rev  6.0.2
Imager X   v3.2.2
Navigation  1.3.29
Redactor    2.7.5
Sprout Fields   3.8.3
Tags    1.0.7
Typed link field    1.0.23
Video Embedder  1.1.4
Workflow    1.5.6

**Comment by riccardolardi** [comment]
Can confirm same issue using latest plugin with latest CraftCMS. Any solution yet?

**Comment by BenParizek** [comment]
Thanks for reporting. This has been addressed in the latest release v3.8.4
