### ISSUE TITLE
Address ignores "Required" in Global set

### ISSUE THREAD

**Issue by benrnorman** [barrelstrength/craft-sprout-fields#121]
### Description (screenshots, logs, ...)

Address (Sprout Fields) field ignores "Required" validation when attached to a Global set. A user can save a Global even if an address field marked as "required" is missing.

### Steps to reproduce

1. Create "Address (Sprout Fields)" field in "Settings" -> "Fields".
2. Add field to a Global set and mark as required in "Settings" -> "Globals".
3. Go to "Globals" and save (without filling a value) OR enter a value in address field, save, then "Clear" and save again.
4. Save succeeds in all scenarios above, and should not.

### Additional info

- Craft version: 3.7.38
- PHP version: 7.4.28
- Database driver & version:  MySQL 5.7.29
- Plugins & versions: 
-- Embedded Assets 2.10.3
-- Redactor 2.10.6
-- SEO 3.7.4
-- Sprout Fields 3.8.5

- We first noticed this issue using Craft 3.5.16, but updated to the above version and the issue persists.
- Initially the field was in a matrix block, but we removed it out to it's own field for testing and issue persists.
- Issue occurs **only** on Global Sets. Elsewhere (Structures, Channels, Singles) a required Address field will properly validate (i.e. not save and show an error) if left blank or cleared.

**Comment by BenParizek** [comment]
This Sprout Address field will be discontinued as we upgrade to Craft 4 and is no longer receiving updates. Craft has added a similar Address field in Craft Commerce and have mentioned they will be adding a [native Address Field](https://github.com/craftcms/cms/discussions/11438) at some point.
