### ISSUE TITLE
Craft 4 Upgrade

### ISSUE THREAD

**Issue by robzor** [barrelstrength/craft-sprout-fields#122]
### The problem (description, use case, screenshots...)
When using the new 'Craft 4 Upgrade' utility (In the Utilities CMS menu item) I cannot upgrade to Craft 4 until this plugin is compatible.

### The solution (that feature you'd like to see)
The plugin updated to Craft 4

### Alternatives you've considered
Using a different field type

**Comment by BenParizek** [comment]
Hey Rob. We're working through Craft 4 support for most of our plugins ([full list of update plans here](https://sprout.barrelstrengthdesign.com/docs/support/road-map.html)). Our focus is on our primary commercial plugins right now and a few of Craft's new features have us choosing to slim down what we support in Sprout fields.

A few thoughts out loud on things we're working through:

- Address Field - Craft has just added a native Address Field, so we're exploring if we can just migrate to that
- Notes Field - Will migrate to Craft's new Field Layout UI Elements
- Email Field - Will probably retire
- URL Field - Will probably retire

**Comment by robzor** [comment]
Thanks @BenParizek ! I'm actually only using the Phone field on this particular site but do regularly use the other fields on other sites. Good to know that it's on your radar, and I will investigate using native fields in the meantime :)

**Comment by digason** [comment]
> Hey Rob. We're working through Craft 4 support for most of our plugins ([full list of update plans here](https://sprout.barrelstrengthdesign.com/docs/support/road-map.html)). Our focus is on our primary commercial plugins right now and a few of Craft's new features have us choosing to slim down what we support in Sprout fields.
> 
> A few thoughts out loud on things we're working through:
> 
> * Address Field - Craft has just added a native Address Field, so we're exploring if we can just migrate to that
> * Notes Field - Will migrate to Craft's new Field Layout UI Elements
> * Email Field - Will probably retire
> * URL Field - Will probably retire

The address field only appears to be an option for Users, not any other element type.

**Comment by BenParizek** [comment]
Yes, unfortunately until Craft makes the Address field a general field type there won't be an easy upgrade path. 

Here's the discussion for a native Address Field type where Brandon says he's planning on adding it at some point:
https://github.com/craftcms/cms/discussions/11438
