### ISSUE TITLE
Argument #1 ($code) must be of type string, null given, called in /app/vendor/commerceguys/addressing/src/Subdivision/SubdivisionRepository.php

### ISSUE THREAD

**Issue by CMeldgaard** [barrelstrength/craft-sprout-fields#123]
### Description (screenshots, logs, ...)
When saving an address, for me in Denmark, i get this error:

``CommerceGuys\\Addressing\\Subdivision\\SubdivisionRepository::createSubdivisionFromDefinitions(): Argument #1 ($code) must be of type string, null given, called in /app/vendor/commerceguys/addressing/src/Subdivision/SubdivisionRepository.php on line 62``

Looks like it `administrativeAreaCode` is set to null, but it must be a string

Im running the latest version on Craft 3.7.53.1

**Comment by digason** [comment]
I've seen this as well.  My solution for the time being is to lock commerceguys/addressing to 1.3.0

**Comment by BenParizek** [comment]
A fix for this has been released in `barrelstrength/sprout-base-fields:v1.4.6`.

Deleting your composer.lock file and running `composer update` will let any Sprout plugins using this pull in the latest, and I'll add this to each respective plugin that uses it in each respective next release. Sprout SEO 4.6.10 already includes this update.
