### ISSUE TITLE
Missing address table after migration from Craft 2 to Craft 3

### ISSUE THREAD

**Issue by KatieMFritz** [barrelstrength/craft-sprout-fields#43]
### Steps to reproduce:

My memory is vague on some of this - sorry!

1. Create some address fields (and other fields) in Craft 2 last year
2. Migrate to Craft 3
3. Lose the plugin in the process, I think?
4. Maybe convert some of the fields to other types?
5. Install the plugin again
6. Notice that address fields can't be added to sections.
7. Delete address fields.
8. Create new address fields and add to globals.
9. Open globals.
10. Error: `The table does not exist: {{%sproutfields_addresses}}`

I'm only using a few other Sprout fields currently, mostly just Notes, so I can remove those if I need to do a clean install of the plugin or something.

### System Info
Windows 10
Wamp64
Also happening on staging (a DigitalOcean droplet managed with ServerPilot)

![screenshot-safs local-2018 04 13-13-02-44](https://user-images.githubusercontent.com/7085184/38748088-fbd5ac8e-3f1a-11e8-9b89-2224737454f6.png)

**Comment by KatieMFritz** [comment]
I started typing the name of the issue and then got distracted! Feel free to rename it to something more meaningful, like "Missing address table after migration from Craft 2 to Craft 3". 🙂

**Comment by pdaleramirez** [comment]
@BenParizek Similar issue on #40 just need to be updated on the latest version.
