### ISSUE TITLE
deprecation error using {{ name }} token instead of FIELDHANDLE

### ISSUE THREAD

**Issue by KatieMFritz** [barrelstrength/craft-sprout-fields#47]
I'm getting the following deprecation error after visiting a CP global set with a Name (Sprout) field.
```
Sprout Fields Notes Field dynamic token `{{ name }}` has been deprecated. 
Use `FIELDHANDLE` instead.
```

Origin: `vendor/craftcms/cms/src/templates/_includes/field.html:11`

**Comment by BenParizek** [comment]
@KatieMFritz 

This error relates to the Notes field. Do you happen to have a Notes field in the same layout? We updated the placeholder syntax for custom styles.

For more info, see the breaking changes section on the upgrades page:
https://sprout.barrelstrengthdesign.com/craft-plugins/fields/docs/getting-started/upgrading-from-craft-2-to-craft-3#changed-fields-breaking-changes

And the new docs on custom styles here:
https://sprout.barrelstrengthdesign.com/craft-plugins/fields/docs/overview/notes-field#custom-styles

**Comment by KatieMFritz** [comment]
When you say layout, do you mean that global set? If so, no, not using notes there., I'm using plain text, Redactor, Assets, Sprout name, Sprout email, Sprout phone, Sprout address, and links using a different plugin. I don't think I'm using any custom styles for Sprout either. 

In my template that uses that info, I'm calling `{{ contactInfo.personName }}`.

**Comment by BenParizek** [comment]
Is it possible you added a Notes field at some point? Or that the deprecation message is older? The only place that deprecation message appears in our code is when outputting the Notes field:
https://github.com/barrelstrength/craft-sprout-fields/blob/v3/src/fields/Notes.php#L89

I expect if you clear deprecation errors and refresh the global set, it won't appear again. Unless maybe you have a Notes field in some other Global set and Craft is preparing all those fields at the same time when it loads the globals area.

**Comment by KatieMFritz** [comment]
The deprecation error continues to come up after clearing the errors. 

I do have a notes field in another global set. I'm using Markdown format and default style. I created the field last week. What should I do?

**Comment by KatieMFritz** [comment]
Hm, I found an older notes field and resaved it with default styles (it already was, but I selected it again). That seemed to help perhaps...

**Comment by BenParizek** [comment]
Alright. Sounds like this is sorted out so I'm going to close it out. 

We'll keep our eye out for any similar behavior.

**Comment by KatieMFritz** [comment]
I started using non-default styles on a couple notes fields, and now I'm getting that deprecation error again:
```
Sprout Fields Notes Field dynamic token `{{ name }}` has been deprecated. Use `FIELDHANDLE` instead.
```
