### ISSUE TITLE
Modern Latin characters breaks field

### ISSUE THREAD

**Issue by lukeyouell** [barrelstrength/craft-sprout-fields#48]
When inserting the charater "ñ" into the Sprout URL field we've noticed that it silently fails and looks to corrupt the field data. 

I used a URL field contained within a matrix field to output social media account links, everything worked fine until the URL included the modern Latin character, this then lead to only one specific block (out of three) being returned in the query.

This was fixed by deleting the field entirely and recreating it without the Sprout URL field.

**Comment by BenParizek** [comment]
@lukeyouell This should be resolved in Sprout Fields v3.1.3 which is now available in the Plugin Store.
