### ISSUE TITLE
Unable to save field after updating a default URL field to Sprout Fields URL field 

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-fields#49]
This specific issue has been resolved for the person who reported it. But let's test when we have chance.

----

I'm running into another issue now with Sprout Fields and Globals. If I try to add a `URL(Sprout)` field to a global set, I can't save it. No error message other than "couldn't save global set".

Creating a brand new `URL (Sprout)` field with default settings worked... 

I wonder if it's because Iconverted a URL to a URL(sprout) field?

If I delete the fields I had and start from scratch, it works. converting doesn't.

**Comment by pdaleramirez** [comment]
@BenParizek i am not able to reproduce the issue on sprout fields and sprout base both on develop branch
