### ISSUE TITLE
Phone field in global set gets wiped out when field is "not translatable"

### ISSUE THREAD

**Issue by KatieMFritz** [barrelstrength/craft-sprout-fields#51]
### Description
When editing Sprout phone fields in a global set, I get the "an unknown error occurred" message. 

Saving a phone number on one site causes the phone number for the other site to get reset to null. 

Changing the field to "translate for each site" gets it to work.

### Steps to reproduce

1. Add a Sprout phone field to a global set in a multisite setup (with two sites). Make the field not translatable. 
2. Type in a phone number for the default site.
3. See "an unknown error occurred" flash at top of screen.
4. Save. Navigating away (within the same site) and coming back, the phone number is still there.
5. On the global set, switch to Site 2
6. Add a phone number for Site 2. See "an unknown error occurred".
7. Save. 
8. Switch back to default site. Phone number field is empty. 

### Additional info

- Craft version: Craft Pro 3.0.8
- PHP version: 7.1.9
- Database driver & version: My SQL 5.7.19
- Plugins & versions: Sprout Fields 3.1.2; can share others on request

**Comment by KatieMFritz** [comment]
This seems to be working with phone now, but I'm getting the same problem with person name and address fields. 

- Craft version: Craft Pro 3.0.9
- PHP version: 7.1.16
- Database driver & version: My SQL 5.7.22
- Plugins & versions: Sprout Fields 3.1.2; can share others on request

**Comment by BenParizek** [comment]
@KatieMFritz This should be resolved for the Phone field and a few others in Sprout Fields v3.1.3 which is now available in the Plugin Store. Thanks for reporting.

**Comment by KatieMFritz** [comment]
Thanks for your quick response to this! Looks good so far. 😄
