### ISSUE TITLE
Add support for CraftQL

### ISSUE THREAD

**Issue by jgeschwendt** [barrelstrength/craft-sprout-fields#52]
It would be great if this plugin worked out of the box with the [CraftQL Plugin](https://github.com/markhuot/craftql)

**Comment by BenParizek** [comment]
@jgeschwendt Happy to consider this at some point but we aren't going to have the time to do this for a while. For the time being, third-party field support is documented here:
https://github.com/markhuot/craftql#third-pary-field-support

Feel free to submit a PR.

**Comment by BenParizek** [comment]
Closing. We'll be adding support for native Craft GraphQL
