### ISSUE TITLE
SproutFields_Link classes do not get updated in the craft_fields table when used on Matrix or SuperTable fields

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-fields#55]
### Description

I ran into this when updating the Straight Up Craft database.

### Steps to reproduce

1. Create SproutFields_Link field on a Matix and Supertable field on C2
2. Upgrade to C3
3. See that several Link fields got updated to `barrelstrength\sproutfields\fields\Url` but a couple didn't.

Let's check if this also happens with any other Sprout Fields.

**Comment by pdaleramirez** [comment]
@BenParizek I have added the upgrade migration for all the fields including the old SproutFields_Link to barrelstrength\sproutfields\fields\Url
