### ISSUE TITLE
Address field modal doesn't render properly when switching country

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-fields#61]
### Description

See: http://share.barrelstrength.co/0Q2y030W1b0X

### Steps to reproduce

1. Open new Address Model
2. Switch country from Afghanistan to United States

The issue is happening for a default address field and for the Address field in the Sprout SEO Globals.

**Comment by pdaleramirez** [comment]
Issue fixed here https://github.com/barrelstrength/craft-sprout-base/commit/1c633896545722e4960a651e947ced7d42f129f5
