### ISSUE TITLE
Impossible to access an attribute ("prefix") on a null variable.

### ISSUE THREAD

**Issue by AbbeyDesign** [barrelstrength/craft-sprout-fields#62]
### Description
I created a name field and added it to a channel. But in the backend if I go to create an entry, I get this error

Impossible to access an attribute ("prefix") on a null variable.

![twig_runtime_error_ _twig_error_runtime](https://user-images.githubusercontent.com/11862097/44660743-94d6ca00-a9d6-11e8-90e9-9406842f32b3.jpg)

### Additional info

- Craft version: latest
- PHP version: 7
- Database driver & version: 5.7
- Plugins & versions:

**Comment by AbbeyDesign** [comment]
After further revue, it happens on channels and structures, but not singles if that helps

**Comment by andrelopez** [comment]
Hi @AbbeyDesign just wanted to let you know that a fix for this issue is available in the latest release of Sprout Fields v3.1.8

Please let us know how it goes.

Best
