### ISSUE TITLE
Address field doesn't set the default chosen country

### ISSUE THREAD

**Issue by frontedbe** [barrelstrength/craft-sprout-fields#63]
### Description
1. When having set a default country in the field's settings, this country doesn't appear as the default country when trying to add an address. [Attached screenshot](https://cl.ly/267e12c6e83a)

2. The 'Hide country dropdown' lightswitch doesn't seem to do what it's supposed to either? I noticed the #22 ticket but doesn't seem the issue is actually resolved in the latest version of the plugin?

### Additional info

- Craft version: 3.0.22
- PHP version: 7.1
- Database driver & version: 
- Plugins & versions: Sprout fields 3.1.8

**Comment by BenParizek** [comment]
@mdominguez These issues are resolved in Sprout Fields v3.1.9, now available in the Plugin Store.
