### ISSUE TITLE
Address Field should support the option to use two letter subdivision code for the Administrative Area (state)

### ISSUE THREAD

**Issue by laurabennett** [barrelstrength/craft-sprout-fields#64]
### Description
commerceguys/addressing allows for getting the abbreviation for states such as NH for New Hampshire, is this possible with sprout fields?

### Additional info

- Craft version: 3.0.24
- PHP version: 7.0.30
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Sprout Fields 3.1.9

**Comment by BenParizek** [comment]
@laurabennett We'll look into adding support for this.

**Comment by BenParizek** [comment]
@laurabennett We've added support for this in a recent release. Please see the docs for all the available variables: https://sprout.barrelstrengthdesign.com/docs/fields/address-field.html

```
{{ entry.addressField.administrativeArea }} {# New Hampshire #}
{{ entry.addressField.administrativeAreaCode }} {# NH #}
```
