### ISSUE TITLE
Editing an address on duplicated entry modifies original

### ISSUE THREAD

**Issue by tomasbreffitt** [barrelstrength/craft-sprout-fields#65]
### Description

When using the "Save as a new entry" feature, the address field is populated with the same reference to an address as the original entry. If you were to edit the address on either the original or new entry, it will edit the address on both.

### Steps to reproduce

1. Create an entry that contains an address field and save.
2. Edit the entry and from the save menu, select Save as a new entry.
3. Edit the new entry to change the address field and save.
4. View the original entry to see the address has been changed.

### Additional info

- Craft version: 3.0.24
- PHP version: 7.2.5
- Database driver & version: MySQL 5.7.22
- Plugins & versions:
  - Admin Bar 3.1.6
  - Amazon S3 1.0.8
  - Asset Rev 6.0.1
  - Button Box 2.0.2
  - CP Clear Cache 1.0.2
  - CP Field Inspect 1.0.4
  - Calendar 2.0.6
  - Country Select 1.1.2
  - Embedded Assets 1.0.2
  - Environment Label 3.1.4
  - Freeform Lite 2.3.2
  - Freeform Pro 2.3.2
  - Incognito Field 1.0.0
  - Mailchimp Subscribe v2.0.2
  - Navigation 1.0.9
  - Position Fieldtype 1.0.13
  - Redactor 2.1.6
  - Redirect plugin for Craft 3 1.0.17
  - SEO 3.3.0
  - Sentry 1.3.3
  - Similar 1.0.3
  - Spoon 3.2.1
  - Sprout Fields 3.1.9
  - SuperSort 3.0.1
  - Super Table 2.0.9
  - Typed link field 1.0.12

**Comment by BenParizek** [comment]
Thanks for reporting @tomasbreffitt 

We'll take a closer look at how Matrix and other similar fields that store their data in another table are handling this.

**Comment by pdaleramirez** [comment]
Committed a fix for this

**Comment by BenParizek** [comment]
@tomasbreffitt This is fixed in the latest release https://github.com/barrelstrength/craft-sprout-fields/releases/tag/v3.1.11
