### ISSUE TITLE
Address Field clear button doesn't work before field is saved

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-fields#68]
### Description

Currently, the clear button works fine after a field is saved but doesn't always behave as expected if it is used while someone is editing and address and has not yet saved the Entry Element the address field is being used on.

### Steps to reproduce

1. Add an address
2. Save it from the modal but don't save the entry
3. Hit clear
4. Save the entry
5. The address you added will appear even though you cleared it before you saved the entry.

**Comment by pdaleramirez** [comment]
@BenParizek I was trying to reproduced the issue and found out that this issue got fixed on version **v3.1.10** i tried to track the commit changes and was unable to see where the changes that fixed the issue. Not sure rebasing commits made it hard to track.

**Comment by pdaleramirez** [comment]
@BenParizek I fixed the bug

Tested adding address to address field on new entry and hitting clear button after, then saving entry. The address field shows empty now after saving the entry.

Also tested on existing entries and clear button. Still same behavior comes up an empty address field.
