### ISSUE TITLE
Address Field modal footer display issue when changing countries

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-fields#69]
### Description

The modal footer of the Address Field modal raises up if a new country is selected that has less address fields in the modal field layout.

It should resize or stay fixed to the bottom, if possible.

http://share.barrelstrength.co/43fbcc5ecc9e

**Comment by pdaleramirez** [comment]
@BenParizek I was trying to reproduced the issue and found out that this issue got fixed on version **v3.1.10** i tried to track the commit changes and was unable to see where the changes that fixed the issue. Not sure rebasing commits made it hard to track.

**Comment by BenParizek** [comment]
@pdaleramirez I'm still seeing this issue. 

For example, It happens when I switch from the United States to Tuvalu for the first time:
http://share.barrelstrength.co/6f20de9dec73

However, if I open Chrome dev tools and then try to do the same thing, it works fine. So it seems that the issue only happens before some action is triggered.
