### ISSUE TITLE
Migration Error When Upgrading From CraftCMS 2 to CraftCMS 3 (settings column missing from plugins table)

### ISSUE THREAD

**Issue by dustinhansen** [barrelstrength/craft-sprout-fields#76]
### Description

I'm attempting to upgrade a client's site from CraftCMS 2 to CraftCMS 3. Everything's gone smoothly except for the Sprout Fields plugin. I updated CraftCMS 2 to the latest version and upgraded Sprout Fields to version 2.2.0 before migrating the database and attempting to upgrade to CraftCMS 3. I get this error message (failed migration) when I try to upgrade:

```
Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'settings' in 'field list'
The SQL being executed was: SELECT id, settings
FROM craft_plugins
WHERE handle='sprout-fields'
LIMIT 1
```

I tried pulling the latest version from Github (3.2.1) into my CraftCMS 2 installation, but when I do that the plugin is missing from the admin panel entirely.

### Steps to reproduce

1. Start with a CraftCMS 2 website with Sprout Fields 2.2.0 installed. Make sure to install any updates for CraftCMS.
2. Dump the database via mysqldump on the old server and restore the database on a new server
3. Set up CraftCMS 3 on the new server and point it to the database you just restored in Step 2.
4. Load CraftCMS 3 in your browser and proceed through the setup process.

### Additional info

- Craft version: 3.1.9
- PHP version: 7.2.10
- Database driver & version: mysqlnd 5.0.12-dev
- Plugins & versions: Sprout Fields 2.2.0

**Comment by BenParizek** [comment]
Hi @dustinhansen 

We just released an updated version of Sprout Fields shortly after you posted this that added Craft 3.1 support. Can you give upgrading to that latest version (v3.2.2) a go? Let us know if you still run into any issues.

**Comment by dustinhansen** [comment]
Thanks for the quick response. I will certainly try this and will get back to you.

**Comment by dustinhansen** [comment]
Hi Ben -- I have a quick question about this. When is the right time to upgrade the plugin? Should 3.2.2 be installed on CraftCMSv2 before we export the database? Or should it be applied in the CraftCMSv3 installation before performing the upgrade procedure? My understanding is that version 3.0 and higher of Sprout Fields is not supported by CraftCMSv2 but I could be mistaken.

**Comment by BenParizek** [comment]
@dustinhansen I'm closing this out as this is most likely an issue with the order of events during the upgrade. If the issue still persists for you, please reply and we'll reopen the discussion and help you get things solved.
