### ISSUE TITLE
Fatal Error upgrading to v3.2.2 on Craft v3.1.10

### ISSUE THREAD

**Issue by richhayler** [barrelstrength/craft-sprout-fields#78]
### Description
I encountered a fatal error when attempting to update to the latest version of Sprout Fields v3.2.2 from 3.2.1. Running craft v3.1.10

Error: Class 'barrelstrength\sproutbaseimport\services\Importers' not found in /var/www/vendor/barrelstrength/sprout-fields/src/SproutFields.php:86

**Comment by GMConsultant** [comment]
idem!

**Comment by GMConsultant** [comment]
Class 'barrelstrength\sproutbase\app\import\services\Importers' not found

**Comment by frontedbe** [comment]
Same

**Comment by BenParizek** [comment]
@richhayler @GMConsultant @mdominguez Thanks for reporting. Just released a fix. This should be resolved in Sprout Fields v3.2.3.
