### ISSUE TITLE
Pull request to fix js issue

### ISSUE THREAD

**Issue by andrelopez** [barrelstrength/craft-sprout-fields#79]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hisb)

**Comment by andrelopez** [comment]
https://github.com/barrelstrength/craft-sprout-base-fields/pull/1

**Comment by pdaleramirez** [comment]
i was able to reproduce js bug and the pull request fixed this isue
