### ISSUE TITLE
Call to a member function setAttributes() on null error when installing Sprout Fields (Craft 2 to Craft 3)

### ISSUE THREAD

**Issue by jamesmacwhite** [barrelstrength/craft-sprout-fields#84]
### Description

When installing Sprout Fields on a Craft 3 project (with a migrated Craft 2 DB) I get the following error during the installation of the plugin.

Not sure what the issue is. I've seen a few other plugins exhibit this issue, but not exactly sure what the error relates to.

Any ideas?

```
Error: Call to a member function setAttributes() on null in /app/vendor/craftcms/cms/src/base/Plugin.php:213
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/Component.php(180): craft\base\Plugin->setSettings(Array)
#1 /app/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('settings', Array)
#2 /app/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(barrelstrength\sproutfields\SproutFields), Array)
#3 /app/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#4 /app/vendor/craftcms/cms/src/base/Plugin.php(127): yii\base\Module->__construct('sprout-fields', Object(craft\web\Application), Array)
#5 [internal function]: craft\base\Plugin->__construct('sprout-fields', Object(craft\web\Application), Array)
#6 /app/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#7 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('barrelstrength\\...', Array, Array)
#8 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('barrelstrength\\...', Array, Array)
#9 /app/vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#10 /app/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('sprout-fields', Array)
#11 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1223): craft\services\Plugins->loadPlugins()
#12 /app/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application->_postInit()
#13 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#14 /app/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#15 /app/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application->__construct(Array)
#16 [internal function]: craft\web\Application->__construct(Array)
#17 /app/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#18 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#19 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#20 /app/vendor/craftcms/cms/bootstrap/bootstrap.php(255): yii\BaseYii::createObject(Array)
#21 /app/vendor/craftcms/cms/bootstrap/web.php(42): require('/app/vendor/cra...')
#22 /app/web/index.php(20): require('/app/vendor/cra...')
#23 {main}
```

### Additional info

- Craft version: 3.1.16
- PHP version: 7.1
- Database driver & version: MySQL 5.6

**Comment by mklishevych** [comment]
I have the same issue.

I think it would be fair to say that it's caused by one of the latest commits and this piece specifically
https://github.com/barrelstrength/craft-sprout-fields/commit/0d56c5723195b95839cf4739509e82d99ebbe1eb#diff-210d33b2ac5a6a2d3399f41c8ec105dcL107

Previously there was an empty `setSettings` method which is now gone and thus it's inherited from the base Plugin class. Parent method expects there will be a settings model which is then used to assign attributes to it. Which is not the case for this plugin. 

I'm pretty tired of all the problems with all of the `sprout-*` plugins that I'm getting and need to spend time on investigating and fixing somehow. Is there a way not to publish a complete garbage as a stable versions?

**Comment by jamesmacwhite** [comment]
This would seem to be the case based on your analysis. Temporary workaround I guess would be to lock composer to the previous version of the plugin before the method was taken out. I'll try that.

**Comment by mklishevych** [comment]
I think it could be a bit of a problem to fix it as there are multiple cross-dependencies and you will need to downgrade those as well. I ended up implementing an autoloader which intercepts the load of this class with my own copy of the file with empty `setSettings` method added.

**Comment by andrelopez** [comment]
Hi @mklishevych 

Could you please confirm us that you're getting this error when migrating from Craft 2?

**Comment by mklishevych** [comment]
Confirm

**Comment by andrelopez** [comment]
Hi @mklishevych @jamesmacwhite 

We just released Sprout Fields v3.2.6 could you please update the plugin and let us know if the issue is fixed?

Best,

**Comment by jamesmacwhite** [comment]
Hi @andrelopez 

Thanks for the quick fix. I've confirmed this error no longer occurs. I started with a fresh copy of the Craft 2 DB prior to testing 3.2.6 and the DB migration went fine without any errors this time.

**Comment by BenParizek** [comment]
Thanks for confirming @jamesmacwhite. Onward!
