### ISSUE TITLE
Phone field not loading in Globals after upgrade from C2 to C3

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-fields#86]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hze3)

**Comment by BenParizek** [comment]
@andrelopez Does this work for non-US phone numbers?

I thought our migration from C2 updated C2 Phone fields to just be Plain Text fields as the new C3 Phone field is more specific in how it handles international numbers and validation.

**Comment by andrelopez** [comment]
You're right @BenParizek I reverted the last commit. This issue is due to the Json::decode class throws an error when the string is not a valid JSON format. This happened when the users try to update the field from a plain text to a Phone Field
