### ISSUE TITLE
Craft 2 to 3 update, error message on new field

### ISSUE THREAD

**Issue by billymedia** [barrelstrength/craft-sprout-fields#88]
### Description
After an update from craft 2 to 3, when trying to create a new field, i click on the new field button and am presented with an error related to this plugin. 
[http://drops.billymedia.co.uk/740914096acf](url)

To get round the issue, i have to add 
```options: contentColumnOptions ?? '',```
to settings.twig

### Steps to reproduce

1. Click new field.

### Additional info

- Craft version: 3.1.28
- PHP version: 7.1.26
- Plugins & versions: Sprout Fields
3.2.9

**Comment by BenParizek** [comment]
@billymedia 

That setting existed briefly in v3.3.1 and was removed in v3.4.0. 

Can you confirm you're upgraded to the latest and clear the Craft template cache and let me know if that gets things resolved?

**Comment by billymedia** [comment]
Fixed, thanks!
