### ISSUE TITLE
Predefined doesn't render value in element index

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-fields#91]
I'm trying to use the predefined field to generate a date. Please note that I'm _not_ using the Predefined Date field for simplicities sake.

I get the following when editing an element, which is correct:
![Screen Shot 2019-09-06 at 10 18 21 am](https://user-images.githubusercontent.com/1221575/64392375-d725f300-d08f-11e9-9b3b-08a81e4def9e.png)

But when trying to show that value on the element's index, I get nothing:
![Screen Shot 2019-09-06 at 10 18 37 am](https://user-images.githubusercontent.com/1221575/64392382-e1e08800-d08f-11e9-8c06-889e3c3d6846.png)

**Comment by engram-design** [comment]
Ah - I now see that I need to re-save all elements again for this value to be set, so its a slightly different issue, but related to https://github.com/barrelstrength/craft-sprout-fields/issues/89

**Comment by BenParizek** [comment]
@engram-design Added to our list to review.

While handy in some cases this field can sometimes feel like a bit of a hack as well. I'd caution to use it sparingly as the more specific scenarios that it tries to solve the more it may just make sense to create a custom field type for the specific need.

**Comment by engram-design** [comment]
For what its worth, we ended up switching back to Preparse. We also noticed that at times the field was outputting the actual twig code, I suppose when a parsing error or something occurred?

I think this sort of field type is a pretty valid use-case, as opposed to a custom field every time you want a calculated value in a field. Having said this, first time I've used this field.
